source=./Modules/Animations.conf              
source=./Modules/Keybinds.conf
source=./Modules/Monitors.conf
source=./Modules/General.conf
source=./Modules/Autostart.conf
source=./Modules/Blur.conf
source=./Modules/Scroller_layout.conf
source=./Modules/Rules.conf
source=./Modules/Environments.conf
source=./Modules/Tagrules.conf
source=./Modules/Master-Stack.conf
source=./Modules/Dwindle_layout.conf
source=./Modules/Shadows.conf
