source=./Animations.conf
source=./Keybinds.conf
source=./Display.conf
source=./General.conf
source=./Autostart.conf
source=./Blur_effects.conf
source=./Scroller_layout.conf
source=./Window_rules.conf
source=./Environments.conf
